#!/usr/bin/env bash

php_ini="/etc/php/7.4/apache2/php.ini"

apt -y install php php-common php-mysql php-gmp php-curl php-intl php-mbstring php-xmlrpc php-gd php-xml php-cli php-zip

apt -y install mariadb-server mariadb-client

sed -i \
    -e 's/max_execution_time = .*/max_execution_time = 300/' \
    -e 's/upload_max_filesize = .*/upload_max_filesize = 100M/' \
    -e 's/post_max_size = .*/post_max_size = 128M/' $php_ini

mysql_secure_installation <<EOF

y
secret
secret
y
y
y
y
EOF
