#!/usr/bin/env bash

# copie le script sur l'instance

usage="$0 ip path : importe un fichier de l'instance localement"

if (( $# < 2 ))
then
  echo $usage
  exit 1
fi

path=$2
ip=$1

scp -i ~/.ssh/id_rsa_jp root@$ip:$path .

