#!/usr/bin/env bash

#if ! type jq
#then
#  echo "jq tool not installed, use apt, dnf or brew to install it"
#  exit 1
#fi

#public_ip=$( terraform output -json tfinstance1_ip | jq -r '.[0]' )

public_ip=$1

echo "Instance public ip:" ${public_ip}

#ssh -i ../ssh-keys/id_rsa_tfkeypair1 \
ssh -i ~/.ssh/id_rsa_jp \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    ubuntu@${public_ip}
